services:
  mare-website:
    build: .

    image: mare-website

    depends_on: [postgres]

    ports: [3000:3000]
    networks: [postgres]

    env_file: .env
    environment:
      DATABASE_URL: postgres://mare:${PG_PASSWORD}@postgres:5432/mare_data

  postgres:
    image: postgres:15

    ports: [5432:5432]
    networks: [postgres]

    environment:
      POSTGRES_DB: mare_data
      POSTGRES_USER: mare
      POSTGRES_PASSWORD: mare

    volumes:
      [myvol:/var/lib/postgresql/data]

  # pgadmin:
  #   image: dpage/pgadmin4:7
  #   ports: [3000:80]
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: mares@snowpity.com
  #     PGADMIN_DEFAULT_PASSWORD: maresilovethem
  #   networks: [postgres]

  # backend for logs
  loki:
    image: grafana/loki:main-be71a80
    command: -config.file=/etc/loki/config.yml
    volumes:
      [loki:/loki]

    ports:
      [3100:3100]

  # frontend
  grafana:
    image: grafana/grafana:latest

    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin


networks:
  postgres:

volumes:
  myvol:
  loki:
